flask_app/projects/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user
from .. import project_client
from ..forms import PostForm, ContactForm
from ..models import User, Post, Project
from ..utils import current_time
projects = Blueprint('projects', __name__)
import  base64

@projects.route("/", methods=["GET", "POST"])
def index():
    return render_template("index.html")

@projects.route("/projects", methods=["GET", "POST"])
def project():
    try:
        username = current_user.username
        projects = project_client.fetch_projects(username)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("{{page_not_found(e)}}"))
    if Project.objects() == None:
        for project in projects:
            proj = Project(
                project_id = project.id,
                title = project.title,
                github_url = project.url,
                description = project.description,
            )
            proj.save()
    
    return render_template("projects.html", projects=projects, forloop = 1)

@projects.route("/aboutme", methods=["GET", "POST"])
def about_me():
    return render_template("about_me.html")


@projects.route("/projects/<project_id>", methods=["GET", "POST"])
def project_detail(project_id):
    try:
        result = Project.objects(project_id = project_id).first()
        print(result)
    except ValueError as e:
        return render_template("project_detail.html", error_msg=str(e))

    form = PostForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        post = Post(
            commenter = current_user._get_current_object(),
            project_title = result.title,
            date=current_time(),
            text = form.text.data,
        )
        post.save()
    
        return redirect(request.path)
    posts = list(Post.objects(project_title = result.title))
    return render_template(
        "project_detail.html", form = form, project = result, posts = posts
    )

@projects.route('/contact', methods=["GET","POST"])
def contact():
    form = ContactForm()
    # here, if the request type is a POST we get the data on contat
    #forms and save them else we return the contact forms html page
    if request.method == 'POST':
        return 'Form posted.'
    else:
        return render_template('contact.html', form=form)

@projects.route("/user/<username>")
def user_detail(username):
    user = User.objects(username = username).first()
    posts = Post.objects(commenter = user)

    return render_template("user_detail.html", username = username, posts = posts)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm
from ..models import User

users = Blueprint('users', __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("projects.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("projects.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("projects.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        # current_user.username = username_form.username.data
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )

flask_app/templates/about_me.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}

<div class="container-fluid">

  <div class="container-fluid float-center">
    <img src="static/AKApicture.png" width="400" 
    height="500" class="rounded mx-auto d-block" alt="...">
  </div>
    <div class="container-fluid float-right">
      <h1 class="text-center">Hello, I'm Joyce (Joy) Tijani<span>!</span></h1>
      <div class="row d-flex justify-content-center align-content-center mr-1">
        <a class="button button-primary button-wide-mobile" href="https://github.com/joytijani">Github</a>
        <a class="button button-primary button-wide-mobile" href="https://www.linkedin.com/in/joyce-tijani/">LinkedIn</a>
      </div>

      <div class="text-center">
        <p>I am a senior computer science student at the University of Maryland College Park with a minor in
          Innovation and Entrepreurship. I graduate in December 2022 with hopes to go full time as a software engineer doing 
        front end development. </p>
      </div>
  </div>
</div>

{% endblock %}>

flask_app/templates/account.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Hey, {{ current_user.username }}!</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <a class="button button-primary button-wide-mobile"> {{ username_form.submit }}</a>
               
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('projects.user_detail', username=current_user.username) }}">
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block style %}
    <link rel="stylesheet" href="static/styles.css">
    {% endblock %}
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Portfolio</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/contact.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}
<div class="contact">
    <h3>Contact Me</h3>
    <form action="{{ url_for('projects.contact') }}" method=post>
        <div>
            <p>
                {{ form.name.label }} <br>
                {{ form.name(placeholder='Full Name') }}
            </p>
            <p>
                {{ form.email.label }} <br>
                {{ form.email(placeholder='Email Address') }}
            </p>
            <p>
                {{ form.subject.label }}<br>
                {{form.subject(placeholder='Subject Line')}}
            </p>
            <p>
                {{ form.message.label }}<br>
                {{ form.message(placeholder='Message') }}
            </p>
            <p>
                {{ form.submit }}
            </p>
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block style %}
{% endblock %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('projects.index') }}">GitHub Portfolio Builder</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('projects.about_me') }}">
                    About Me
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('projects.contact') }}">
                    Contact Me
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('projects.project') }}">
                    Projects
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block style %}
    <link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}
<body>
    <section class="hero text-center text-light">
        <div class="hero-particles-container">
            <canvas id="hero-particles"></canvas>
        </div>
        <div class="container-sm">
            <div class="hero-inner">
                <div class="hero-copy">
                    <h1 class="hero-title mt-0">Hey, Welcome to the Portfolio Builder!</h1>
                    <p class="hero-paragraph">Looking to get started? Click A Button Below to begin!</p>
                    <div class="d-grid gap-3">
                        <a class="button button-primary button-wide-mobile" href="{{ url_for('users.register') }}">Register For An Account Here</a>
                        <a class="button button-primary button-wide-mobile" href="{{ url_for('users.login') }}">Already have an account? Then Log In</a>
                    </div>
                </div>
            </div>
        </div>
</body>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}
<div class="row">
    <div class="login-col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="login-col">
        If you <b>don't</b> have an account, then <a class="button button-primary button-wide-mobile" href="{{ url_for('users.register') }}">Register!</a> 
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                <p style="font-weight: bold;">USERNAME SHOULD MATCH GITHUB USERNAME</p>
                <div class="login-col">
                    {{ form.username.label(class="form-control-label green-text") }}
                    {{ form.username(class="form-control form-control-md") }}
                </div>

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <div class="login-col">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control form-control-lg") }}
                </div>

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/project_detail.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}

{# Display card for Project #}
<div class="container-fluid">
  <div class="row d-flex justify-content-center align-content-center mr-1">
    <h1> {{ project.title }}</h1>
  </div >
  <h2> {{ project.description }}</h2>
</div>


{# Comments About Project #}
<div class="row">
  <div class="col-md-12">
    <h1> Comments </h1>
    <ul class="media-list">
      {% for post in posts %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ post.date }}</small>
          </span>
          <a href="{{ url_for('projects.user_detail', username=post.commenter.username) }}">
            <strong>@{{ post.commenter.username }}</strong>
          </a>
          <p>
            {{ post.text }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{# Comment Form #}
{% if current_user.is_authenticated %}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endblock content %}

flask_app/templates/projects.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}

<div class="m-4">
      <div class="row mb-4">
          {# All my projects should go on this page #}
          <div class="container-fluid">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                {% if forloop %}
                {% for project in projects %}
                <div class="item {% if forloop.counter == 1 %}active{% endif %}" id="slide{{ forloop.counter }}">
                  <h1>{{ project.title }}</h1>
                  <div class="container-fluid" >
                    <div class="row d-flex justify-content-center align-content-center mr-1">
                      <a class="button button-primary button-wide-mobile" href="{{ project.url}}">Github Repo</a>
                      <a class="button button-primary button-wide-mobile" href="{{ url_for('projects.project_detail', project_id = project.id) }}">Project Link</a>
                    </div>
                  </div>
                </div>
                {% endfor %}
                {% endif %}
              </div>
            </div>
            </div>
      </div>
</div>
{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block style %}
<link rel="stylesheet" href="static/styles.css">
{% endblock %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Registration</h1>
    </div>
</div>
<div class="row">
    <div class="login-col">
        If you already have an account, then just <a class="button button-primary button-wide-mobile" href="{{ url_for('users.login') }}">Log In!</a> 
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                <div class="login-col">
                    {{ form.username.label(class="form-control-label") }}
                    {{ form.username(class="form-control form-control-lg") }}
                </div>
                
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <div class="login-col">
                    {{ form.email.label(class="form-control-label") }}
                    {{ form.email(class="form-control form-control-lg") }}
                </div>
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <div class="login-col">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control form-control-lg") }}
                </div>
                
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                <div class="login-col">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                </div>

                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Comments</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Project Comments </h1>
        <ul class="media-list">
            {% for project in projects %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ project.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('projects.project_detail', project_id=post.project_id) }}">
                            {{ project.project_title }}
                        </a>
                    </strong>
                    <p>
                        {{ project.text }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}